# Site settings
title: Oberholzer.it # site title
description: >- # site description
  A blog about advanced concepts in computer science, including topics related to cyber security and low level programming. Explore the inner workings of computer science and gain a deeper understanding of key concepts with in-depth analysis and explanation.
lang: en-US # default lang
timezone: Europe/Zurich # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/LuckLATL/lucklatl.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Oberholzer.it # author name
  bio: >- # tell to the world
    Hey there! Join in on the exciting journey through the realms of code and cybersecurity, where we unlock the power to protect and conquer the virtual frontier.
  username: Luck_LATL # general username
  github: lucklatl # github username
  # twitter: twitter_username # twitter username
  # facebook: facebook_username # facebook username
  email: blog@oberholzer.it # email adress
  avatar: /assets/img/avatar_common.png # change with your own avatar

# URL settings
url: "https://oberholzer.it" #
baseurl:
permalink: /posts/:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
